version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    container_name: embedding
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
              flask run --host=0.0.0.0"
    restart: always